# Symbol       Value
# I             1
# V             5
# X             10
# L             50
# C             100
# D             500
# M             1000


class Solution:
    def romanToInt(self, s):
        
        symbol = {
            "I" : 1,
            "V" : 5,
            "X" : 10,
            "L" : 50,
            "C" : 100,
            "D" : 500,
            "M" : 1000,
            "IX" : 9,
            "IV" : 4,
            "XL" : 40,
            "XC" : 90,
            "CD" : 400,
            "CM" : 900
                }
        
        num = 0
        i = 0
        while i < len(s):
            
            if i+1<len(s) and s[i:i+2] in symbol:
                num += symbol[s[i:i+2]]
                i+=2
            else:
            #print(i)
                num += symbol[s[i]]
                i+=1
        return num   
s = Solution()
print(s.romanToInt("IIIDX"))


